baseURL = "https://sdellavi.github.io/"
relativeURLs = true
title = "Stefano DellaVigna"
theme = "academimal"
layoutDir = "layouts"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Daniel E. Koshland, Sr. Distinguished Professor of Economics and Professor of Business Administration, University of California, Berkeley <br> <br> Chair of the Economics Department"
    logo = "images/stefano-dellavigna.jpg"
    faviconVersion = "4"
    logoVersion = "1"
    
